export const PUBLIC_LAYOUT_ROUTES = [
  { path: '/', page: 'home' },
  { path: '/collections/:slug', page: 'collection' },
  { path: '/products/:id', page: 'productDetail' },
  { path: '/new-in', page: 'merchandising', props: { pageKey: 'new-in' } },
  { path: '/bestsellers', page: 'merchandising', props: { pageKey: 'bestsellers' } },
  { path: '/sale', page: 'merchandising', props: { pageKey: 'sale' } },
  { path: '/campaigns/:slug', page: 'editorial', props: { sectionKey: 'campaigns' } },
  { path: '/lookbook/:slug', page: 'editorial', props: { sectionKey: 'lookbook' } },
  { path: '/occasions/:slug', page: 'editorial', props: { sectionKey: 'occasions' } },
  { path: '/about', page: 'info', props: { pageKey: 'about' } },
  { path: '/size-guide', page: 'info', props: { pageKey: 'size-guide' } },
  { path: '/delivery', page: 'info', props: { pageKey: 'delivery' } },
  { path: '/returns', page: 'info', props: { pageKey: 'returns' } },
  { path: '/faq', page: 'info', props: { pageKey: 'faq' } },
  { path: '/contact', page: 'info', props: { pageKey: 'contact' } },
  { path: '/track-order', page: 'info', props: { pageKey: 'track-order' } },
  { path: '/wishlist', page: 'wishlist' },
  { path: '/account', page: 'account' },
  { path: '/cart', page: 'cart' },
  { path: '/checkout', page: 'checkout' },
  { path: '/login', page: 'login' },
  { path: '/register', page: 'register' },
  { path: '/orders', page: 'orders' },
];
