export const INITIAL_PRODUCT_FORM = {
  slug: '',
  sku: '',
  status: 'active',
  name: '',
  description: '',
  collectionSlug: '',
  collectionSlugs: [],
  price: '',
  compareAtPrice: '',
  coverImage: '',
  variants: 'XS |  |  | 0\nS |  |  | 0\nM |  |  | 0\nL |  |  | 0',
  images: '',
  styleTags: '',
  material: '',
  fitNotes: '',
  seoTitle: '',
  seoDescription: '',
  enName: '',
  enDescription: '',
  enMaterial: '',
  enFitNotes: '',
  enSeoTitle: '',
  enSeoDescription: '',
  isNew: true,
  isBestSeller: false,
  isOnSale: false,
  trendingScore: '',
};

export const INITIAL_COLLECTION_FORM = {
  slug: '',
  title: '',
  description: '',
  image: '',
  featuredKeywords: '',
  seoHeading: '',
  seoBody: '',
  enTitle: '',
  enDescription: '',
  enSeoHeading: '',
  enSeoBody: '',
  sortPriority: '',
  isActive: true,
};

export const INITIAL_HOME_FORM = {
  brandName: '',
  announcement: '',
  footerHeading: '',
  footerDescription: '',
  storeHoldDurationLabel: '',
  backgroundImage: '',
  heroImage: '',
  heroEyebrow: '',
  heroTitle: '',
  heroDescription: '',
  heroPrimaryCtaLabel: '',
  heroPrimaryCtaTo: '',
  heroSecondaryCtaLabel: '',
  heroSecondaryCtaTo: '',
  heroStats: '',
  sectionControls: '',
  campaignEyebrow: '',
  campaignTitle: '',
  campaignDescription: '',
  campaignTo: '',
  campaignCtaLabel: '',
  uspItems: '',
  occasions: '',
  reviews: '',
  newsletterEyebrow: '',
  newsletterTitle: '',
  newsletterDescription: '',
  ugcPosts: '',
};

export const HOME_SECTION_CONTROL_OPTIONS = [
  { key: 'campaigns', label: 'Chiến dịch nổi bật', metric: 'Campaign' },
  { key: 'newIn', label: 'Mới về', metric: 'Sản phẩm mới' },
  { key: 'bestsellers', label: 'Bán chạy', metric: 'Sản phẩm bán chạy' },
  { key: 'categories', label: 'Danh mục', metric: 'Điều hướng' },
  { key: 'occasions', label: 'Theo dịp', metric: 'Landing marketing' },
  { key: 'reviews', label: 'Đánh giá', metric: 'Social proof' },
  { key: 'ugc', label: 'UGC', metric: 'Social content' },
];

export const INITIAL_MERCH_FORM = {
  eyebrow: '',
  title: '',
  description: '',
  image: '',
};

export const INITIAL_EDITORIAL_FORM = {
  eyebrow: '',
  title: '',
  description: '',
  image: '',
  bullets: '',
  ctaLabel: '',
  ctaTo: '',
};

export const INITIAL_INFO_FORM = {
  eyebrow: '',
  title: '',
  intro: '',
  image: '',
  sections: '',
  tableHeaders: '',
  tableRows: '',
  faqs: '',
  cards: '',
  steps: '',
  mapTitle: '',
  mapAddress: '',
  mapCoordinates: '',
  mapUrl: '',
  mapEmbedUrl: '',
};
