FROM node:18-bookworm-slim AS frontend-build

WORKDIR /app

COPY frontend/package*.json ./
RUN npm ci --include=optional

COPY frontend/ ./
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=frontend-build /app/dist /usr/share/nginx/html
